### ISSUE TITLE
mixup ratio clipping?

### ISSUE THREAD

**Issue by veroveroxie** [ChrisAllenMing/Mixup_for_UDA#1]
Nice work!  Could you please explain the mixup ratio clipping operation used in the code? Why do you clip it to [0.,0.2] and [0.8,1.0]?  Is there any heuristics in choosing the alpha or mixup ratio?

**Comment by ChrisAllenMing** [comment]
This operation is based on the heuristic that those samples approaching source or target domain are easier to discriminate, which makes domain discriminator easier to converge and, at the same time, provides enough information of the status between two domains.

**Comment by veroveroxie** [comment]
thank you!
