### ISSUE TITLE
error

### ISSUE THREAD

**Issue by besaman** [ChrisAllenMing/Mixup_for_UDA#6]
Hi, thanks for sharing the code.
However, I'm getting an error 
```
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main()
  File "main.py", line 131, in main
    DM_ADA_trainer.train()
  File "/home/usr/code/Test/Mixup/trainer_mixed.py", line 290, in train
    errF.backward()
  File "/home/usr/.conda/envs/emad/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/usr/.conda/envs/emad/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [16, 1, 1, 4]], which is output 0 of UnsqueezeBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

can you suggest the reason of this error?

**Comment by ChrisAllenMing** [comment]
I think it's mainly due to the mismatched version of PyTorch. The DM-ADA code requires the version of PyTorch to be 0.4.0/0.4.1, and it may not support the newer versions.

**Comment by besaman** [comment]
Thank you for your reply.
Another question please: why you set `retain_graph=True` for `backward()` function in all losses except for `errF` ?

**Comment by ChrisAllenMing** [comment]
This is in order to retain all the forward intermediate computational results that are needed to compute the gradients for the subsequent network modules, while since the 'errF' is the last loss to optimize, we do not need to retain the computational graph anymore when back-propagate its gradients.

**Comment by besaman** [comment]
thanks
